export const BUSINESS_ENDPOINTS = {
  REGISTER: '/businesses/register',
  GET_ALL: '/businesses',
  GET_BY_ID: '/businesses/:id',
  UPDATE_BRAND_DETAILS: '/businesses/:id/brand-details',
  UPDATE_APPEARANCE: '/businesses/:id/appearance',
  UPDATE_LOCATION: '/businesses/:id/location',
  UPDATE_GENERAL: '/businesses/:id/general',
  UPDATE_BOOKING_POLICIES: '/businesses/:id/booking-policies',
  UPDATE_BOOKING_SETUP: '/businesses/:id/booking-setup',
  UPDATE_BOOKING_CUSTOMIZATION: '/businesses/:id/booking-customization',
  UPDATE_VISIBILITY: '/businesses/:id/visibility',
  UPDATE_TEAM_NOTIFICATIONS: '/businesses/:id/team-notifications',
  UPDATE_CUSTOMER_NOTIFICATIONS: '/businesses/:id/customer-notifications',
  UPDATE_NOTIFICATION_CUSTOMIZATION: '/businesses/:id/notification-customization',
  UPDATE_BUSINESS_HOURS: '/businesses/:id/business-hours',
  UPDATE_BUSINESS_LINKS: '/businesses/:id/links',
  UPDATE_CONTACT_DETAILS: '/businesses/:id/contact-details',
  UPDATE_BRAND_DETAILS_IMAGES: '/business/:id/brand-details-images',
  UPDATE_GALLERY_PHOTOS: '/business/:id/gallery-photos',
} as const;
