export const USER_ENDPOINTS = {
  LOGIN: '/users/login',
  REFRESH: '/users/refresh',
  LOGOUT: '/users/logout',
  ME: '/users/me',
  INVITE: '/users/invite',
  BUSINESS_OWNERS: '/users/business-owners',
  BY_ROLE: '/users/by-role',
  UPDATE_WORKING_HOURS: '/users/:userId/working-hours',
  BUSINESS_USERS: '/users/business/:businessId',
  REQUEST_INVITE_OTP: '/users/invite/request-otp',
  ACCEPT_INVITE: '/users/invite/accept',
  FREE_SLOTS: '/users/free-slots/:userId',
  UPDATE_AVATAR: '/users/:userId/avatar',
} as const;
