services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - rustfs_data:/data
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin
    command: --access-key admin --secret-key admin /data

volumes:
  rustfs_data:
