import { Customer } from '@pikslots/domain';

const now = new Date();

const EMPTY_LINKS = {
  Website: '',
  Instagram: '',
  Facebook: '',
  Tiktok: '',
  X: '',
  Youtube: '',
  LinkedIn: '',
};

export const CUSTOMER_TEST_DATA: Customer[] = [
  // ── business-1 customers ────────────────────────────────────────────────
  Customer.create({
    id: 'customer-1',
    name: { firstName: 'Alice', lastName: 'Walker' },
    email: 'alice.walker@example.com',
    additionalEmail: null,
    primaryPhone: '+1-555-0101',
    additionalPhone: null,
    company: 'Walker Design Co.',
    country: 'USA',
    address: '12 Birch Street',
    city: 'Austin',
    state: 'TX',
    zipCode: '73301',
    notes: 'Prefers appointments in the morning.',
    customerSocialLinks: {
      ...EMPTY_LINKS,
      Website: 'https://alicewalker.example.com',
      Instagram: 'https://instagram.com/alicewalker',
    },
    profileImageUrl: 'https://cdn.example.com/avatars/customer-1.jpg',
    businessId: 'business-1',
    createdBy: 'user-standard-1',
  }),
  Customer.create({
    id: 'customer-2',
    name: { firstName: 'Brian', lastName: 'Chen' },
    email: 'brian.chen@example.com',
    additionalEmail: 'b.chen.alt@example.com',
    primaryPhone: '+1-555-0102',
    additionalPhone: '+1-555-0199',
    company: null,
    country: 'USA',
    address: null,
    city: 'Austin',
    state: 'TX',
    zipCode: null,
    notes: null,
    customerSocialLinks: EMPTY_LINKS,
    profileImageUrl: null,
    businessId: 'business-1',
    createdBy: 'user-admin-1',
  }),
  // Minimal customer — most optional fields null, to exercise nullable
  // field handling in mappers/DTOs.
  Customer.create({
    id: 'customer-3',
    name: { firstName: 'Priya', lastName: 'Nair' },
    email: null,
    additionalEmail: null,
    primaryPhone: null,
    additionalPhone: null,
    company: null,
    country: null,
    address: null,
    city: null,
    state: null,
    zipCode: null,
    notes: null,
    customerSocialLinks: EMPTY_LINKS,
    profileImageUrl: null,
    businessId: 'business-1',
    createdBy: 'user-enhanced-1',
  }),

  // ── business-2 customer — for cross-business authorization denial ──────
  Customer.create({
    id: 'customer-business-2-1',
    name: { firstName: 'Derek', lastName: 'Owusu' },
    email: 'derek.owusu@example.com',
    additionalEmail: null,
    primaryPhone: '+1-555-0210',
    additionalPhone: null,
    company: 'Owusu Consulting',
    country: 'USA',
    address: '88 Maple Ave',
    city: 'Denver',
    state: 'CO',
    zipCode: '80202',
    notes: null,
    customerSocialLinks: {
      ...EMPTY_LINKS,
      LinkedIn: 'https://linkedin.com/in/derekowusu',
    },
    profileImageUrl: null,
    businessId: 'business-2',
    createdBy: 'user-business-owner-2',
  }),

  // ── Soft deleted customer — reconstitute() needed because create()
  //    always sets isDeleted: false ─────────────────────────────────────
  Customer.reconstitute({
    id: 'customer-deleted-1',
    name: { firstName: 'Grace', lastName: 'Kim' },
    email: 'grace.kim@example.com',
    additionalEmail: null,
    primaryPhone: '+1-555-0303',
    additionalPhone: null,
    company: null,
    country: 'USA',
    address: null,
    city: 'Austin',
    state: 'TX',
    zipCode: null,
    notes: 'Requested account removal.',
    customerSocialLinks: EMPTY_LINKS,
    profileImageUrl: null,
    businessId: 'business-1',
    createdAt: now,
    createdBy: 'user-standard-1',
    updatedAt: now,
    updatedBy: 'user-admin-1',
    deletedAt: now,
    deletedBy: 'user-admin-1',
    isDeleted: true,
  }),
];
