import { User } from '@pikslots/domain';

export let USER_TEST_DATA: User[] = [
  User.create({
    id: 'user-platform-owner-1',
    username: 'platform_owner',
    password: 'hashed_password_2',
    businessId: null,
    name: { firstName: 'Alice', lastName: 'Walker' },
    email: 'alice@pikslots.com',
    phone: '+1000000001',
    role: 'Platform Owner',
    bookingUrl: 'alice-walker',
    createdBy: 'system',
  }),
  User.create({
    id: 'user-business-owner-1',
    username: 'business_owner',
    password: 'hashed_password_2',
    businessId: 'business-1',
    name: { firstName: 'Bob', lastName: 'Smith' },
    email: 'bob@acme.com',
    phone: '+1000000002',
    role: 'Business Owner',
    bookingUrl: 'bob-smith',
    createdBy: 'user-platform-owner-1',
  }),
  User.create({
    id: 'user-admin-1',
    username: 'admin_user',
    password: 'hashed_password_3',
    businessId: 'business-1',
    name: { firstName: 'Carol', lastName: 'Jones' },
    email: 'carol@acme.com',
    phone: '+1000000003',
    role: 'Admin',
    bookingUrl: 'carol-jones',
    createdBy: 'user-business-owner-1',
  }),
  User.create({
    id: 'user-enhanced-1',
    username: 'enhanced_user',
    password: 'hashed_password_4',
    businessId: 'business-1',
    name: { firstName: 'David', lastName: 'Brown' },
    email: 'david@acme.com',
    phone: '+1000000004',
    role: 'Enhanced',
    bookingUrl: 'david-brown',
    createdBy: 'user-admin-1',
  }),
  User.create({
    id: 'user-standard-1',
    username: 'standard_user',
    password: 'hashed_password_5',
    businessId: 'business-1',
    name: { firstName: 'Eve', lastName: 'Davis' },
    email: 'eve@acme.com',
    phone: '+1000000005',
    role: 'Standard',
    bookingUrl: 'eve-davis',
    createdBy: 'user-admin-1',
  }),
  User.create({
    id: 'user-no-access-1',
    username: 'no_access_user',
    password: 'hashed_password_6',
    businessId: 'business-1',
    name: { firstName: 'Frank', lastName: 'Miller' },
    email: 'frank@acme.com',
    phone: '+1000000006',
    role: 'No Access',
    bookingUrl: 'frank-miller',
    createdBy: 'user-admin-1',
  }),
];
